export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_DISAPPEAR = "REGISTER_DISAPPEAR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const UNDO_FLAG = "UNDO_FLAG";

export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_COLLA_PROJECT_LIST = "GET_COLLA_PROJECT_LIST";

export const SEARCH_COLLA_PROJECT_LIST = "SEARCH_COLLA_PROJECT_LIST";
export const UPLOAD_RESUME = "UPLOAD_RESUME";

export const SEARCH_PROJECT_LIST = "SEARCH_PROJECT_LIST";

export const POST_PROJECT_ROLE = "POST_PROJECT_ROLE";
export const POST_PROJECT_ROLE_FAIL = "POST_PROJECT_ROLE_FAIL";

export const CHANGE_PROJECT_ROLE = "CHANGE_PROJECT_ROLE";
export const CHANGE_PROJECT_ROLE_FAIL = "CHANGE_PROJECT_ROLE_FAIL";

export const SEND_INVITATION = "SEND_INVITATION";

export const APPLY_ROLE = "APPLY_ROLE";

export const APPPROVE_APPLICATION = "APPPROVE_APPLICATION";

export const DECLINE_APPLICATION = "DECLINE_APPLICATION";

export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
export const DECLINE_INVITATION = "DECLINE_INVITATION";

export const FINISH_PROJECTS = "FINISH_PROJECTS";

export const CHANGE_PROJECTS = "CHANGE_PROJECTS";
export const FETCH_RESUME_NAME = "FETCH_RESUME_NAME";

export const UNDO_CHANGE = "UNDO_CHANGE";

